# Generated by Django 6.0.2 on 2026-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(default='仮タイトル', max_length=255, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
