# Generated by Django 5.2.13 on 2026-04-25 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('video', '動画'), ('music', '音楽'), ('other', 'その他')], max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='月額料金（円）')),
                ('custom_name', models.CharField(blank=True, max_length=255, verbose_name='サービス名（手入力）')),
                ('currency', models.CharField(choices=[('JPY', '円'), ('USD', 'ドル'), ('EUR', 'ユーロ')], default='JPY', max_length=3, verbose_name='通貨')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='更新間隔')),
                ('interval_unit', models.CharField(choices=[('month', 'ヶ月'), ('year', '年')], default='month', max_length=10, verbose_name='単位')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
