# Generated by Django 6.0.2 on 2026-04-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('JPY', '円'), ('USD', 'ドル'), ('EUR', 'ユーロ')], default='JPY', max_length=3, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='料金'),
        ),
    ]
