# Generated by Django 5.2.13 on 2026-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_service_plan_service_price_alter_service_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='料金（ユーザー設定）'),
        ),
    ]
