# Generated by Django 5.2.13 on 2026-05-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_category_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('entertainment', 'エンタメ'), ('life', '生活'), ('insurance', '保険'), ('other', 'その他')], default='entertainment', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.category'),
        ),
    ]
