# Generated by Django 6.0.2 on 2026-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_created_at_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='renewal_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval_unit',
            field=models.CharField(choices=[('month', 'ヶ月'), ('year', '年')], default='month', max_length=10, verbose_name='単位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval_value',
            field=models.IntegerField(default=1, verbose_name='更新間隔'),
            preserve_default=False,
        ),
    ]
