# Generated by Django 5.2.13 on 2026-04-25 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_service_remove_subscription_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval_unit',
            field=models.CharField(choices=[('month', 'ヶ月'), ('year', '年')], default='month', max_length=10, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='更新間隔'),
        ),
    ]
